# What happens?

stages:
  - build
  - push2artifactory
  - deploy

variables:
  artifactory_appdir: testapps
  artifactpath: target
  appname: test-logging-mdc
  javaargs: -DlogstashSocket=oracleadmintst.gksm.local:17000 -Dtest=appolol

default:
  before_script:
    - export JAVA_HOME=/opt/oracle/java/latest_17

# workflow:
#   rules:
#     - if: $CI_COMMIT_TAG

build-job:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean
    - mvn $MAVEN_CLI_OPTS package -f pom.xml -DskipTests
  artifacts:
    paths:
      - ${artifactpath}/${appname}.jar
    expire_in: 5 min

artifactory-upload-job:
  stage: push2artifactory
  script:
    - >
      curl -f -v
      --user ${ARTIFACTORY_USER}:${ARTIFACTORY_PASS}
      -T ./${artifactpath}/${appname}.jar
      -XPUT ${ARTIFACTORY_URL}/${ARTIFACTORY_PATH}/${artifactory_appdir}/${appname}.jar;

deploy-job:
  stage: deploy
  variables:
    ARTFILE: ${ARTIFACTORY_URL}/${ARTIFACTORY_PATH}/${artifactory_appdir}/${appname}.jar
    PROJECT: ${PROJECT}
  trigger: 
    project: waadmin/helm/charts/java-apps
    branch: master
